### ISSUE TITLE
Add Clojure/Maven tools

### ISSUE THREAD

**Issue by jlesquembre** [mikeroyal/NixOS-Guide#9]
Thanks for writing this guide, quite useful.

I'd like to see Clojure in the list of programming languages. To my knowledge, there are currently 2 active projects to support Clojure in the Nix ecosystem (I'm the author of the first one):

- https://github.com/jlesquembre/clj-nix
- https://github.com/bevuta/clojure-nix-locker

I'd also add mvn2nix to the Java list:

- https://github.com/fzakaria/mvn2nix

**Comment by mikeroyal** [comment]
Made a PR thank you for your suggestion. If you have anymore suggestions feel to make another issue or PR.
